services:
  - type: web
    name: vue3-wb-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22
